### PR TITLE
GH-1807 [Django Upgrade] LDAP auth error: authenticate() missing 1 required positional argument: 'request'

### PR DESCRIPTION
**Pull request by agl29**
## What changes were proposed in this pull request?
 - GH-1807 - [Django Upgrade] LDAP auth error: authenticate() missing 1 required positional argument: 'request'
- `request` argument is added

### CODE REVIEW

**Review by romainr — COMMENTED** [review]
Breaks Python2?

**Review by romainr — APPROVED** [review]
Or actually a miss from upgrade to 2?

**Comment by agl29** [comment]
> Or actually a miss from upgrade to 2?

yes, when upgrading from 2.0 to 2.1. commit -> https://github.com/cloudera/hue/commit/eff69b580df0537945b557b9716c7135accb2cef

**Comment by romainr** [comment]
Ok, but we will now brake with Django 2-3 so? (need to support both)

**Comment by agl29** [comment]
> Ok, but we will now brake with Django 2-3 so? (need to support both)

So, this commit is wrong (I am not getting, where it is breaking)? I think this will work in both Django 2 and 3

**Comment by romainr** [comment]
Let's a add a test so to be sure.

And here if have ifs/elses depending on if on Django 1 or >
https://github.com/cloudera/hue/commit/eff69b580df0537945b557b9716c7135accb2cef

**Review by Akhilsnaik — APPROVED** [review]
I can confirm the Fix works well in Python-3 and IMHO it has to work in Python-2 too .

**Comment by romainr** [comment]
Long story short, this fix should fix Django 3 but break Django 1 IIRC (so to add `request` only for Python 3, and should be easy to add a small test for both)

File: desktop/core/src/desktop/auth/backend.py [hunk 1]
```diff
@@ -579,7 +579,10 @@ def authenticate(self, request=None, username=None, password=None, server=None):
     try:
       allowed_group = self.check_ldap_access_groups(server, username)
       if allowed_group:
-        user = self._backend.authenticate(username=username, password=password)
+        if sys.version_info[0] > 2:
+          user = self._backend.authenticate(request, username=username, password=password)
+        else:
+          user = self._backend.authenticate(username=username, password=password)
```
Comment (agl29) [inline desktop/core/src/desktop/auth/backend.py:585]: Yes, @romainr unit test was not passing with 'request' argument for Django 1. Thanks a lot.

**Review by romainr — APPROVED** [review]
Really nice one!
