### ISSUE TITLE
MockRequest instance has no attribute 'fs'

### ISSUE THREAD

**Issue by stephbat** [cloudera/hue#1754]
Hue version 4.8.0 (docker)

When I execute a script in PIG editor or a spark program in SPARK editor, I always get the message "MockRequest instance has no attribute 'fs'". It seems that there's no impact on the behaviour.
In the logs, there's this error:
```
[09/Feb/2021 10:30:48 +0100] decorators   ERROR    Error running fetch_result_data
Traceback (most recent call last):
  File "/usr/share/hue/desktop/libs/notebook/src/notebook/decorators.py", line 114, in wrapper
    return f(*args, **kwargs)
  File "/usr/share/hue/desktop/libs/notebook/src/notebook/api.py", line 318, in fetch_result_data
    response = _fetch_result_data(request.user, notebook, snippet, operation_id, rows=rows, start_over=start_over)
  File "/usr/share/hue/desktop/libs/notebook/src/notebook/api.py", line 329, in _fetch_result_data
    'result': get_api(request, snippet).fetch_result(notebook, snippet, rows, start_over)
  File "/usr/share/hue/desktop/libs/notebook/src/notebook/models.py", line 517, in get_api
    return ApiWrapper(request, snippet)
  File "/usr/share/hue/desktop/libs/notebook/src/notebook/models.py", line 503, in __init__
    self.api = _get_api(request, snippet)
  File "/usr/share/hue/desktop/libs/notebook/src/notebook/connectors/base.py", line 436, in get_api
    return OozieApi(user=request.user, request=request)
  File "/usr/share/hue/desktop/libs/notebook/src/notebook/connectors/oozie_batch.py", line 58, in __init__
    self.fs = self.request.fs
AttributeError: MockRequest instance has no attribute 'fs'
```

What is the reason of this message ? Maybe a miss configuration in HUE ?
thanks in advance

**Comment by Akhilsnaik** [comment]
@stephbat  ,
i can see the operation actually runs as an oozie job and  probably the hdfs related configs are not set in hue.ini ?
https://github.com/cloudera/hue/blob/master/desktop/conf.dist/hue.ini#L1130-L1139

see if adding your hdfs configs as below helps or not  

```
[hadoop]
[[hdfs_clusters]]
[[[default]]]
fs_defaultfs=hdfs://host.example.com:8020
webhdfs_url=http://host.example.com:50070/webhdfs/v1
security_enabled=false
temp_dir=/tmp

```

**Comment by stephbat** [comment]
Hue is working with HDP 3.1.4

hadoop is configured like below in hue.ini
`[hadoop]
[[hdfs_clusters]]
[[[default]]]
fs_defaultfs=hdfs://dbdne
webhdfs_url=http://hue-server:14000/webhdfs/v1
security_enabled=true
ssl_cert_ca_verify=false
hadoop_conf_dir="/usr/hdp/current/hadoop-client/conf/"` 

and 'dbdne' is defined in the /usr/hdp/current/hadoop-client/conf/core-site.xml
`    <property>
      <name>fs.defaultFS</name>
      <value>hdfs://dbdne</value>
    </property>`

**Comment by romainr** [comment]
Thanks for the report!

This is probably related to:
https://github.com/cloudera/hue/blob/master/desktop/libs/notebook/src/notebook/models.py#L276

And we could add in the __init__()?
https://github.com/cloudera/hue/blob/master/desktop/libs/notebook/src/notebook/models.py#L727

```
class MockRequest():
  def __init__(self, user, fs=None, jt=None):
    self.user = user
    self.fs = fs
    self.jt = jt
    self.POST = {}
```

Would you be able to send a PR for it?

Note: it fails in the the result result, but IIRC there is no results with this API, only a dump of the log output
Note 2: there are also some other MockRequest classes we could unify, but can be done in Hue 5 in a an easier way

**Comment by stephbat** [comment]
@romainr : Do you confirm that you want to change the code of the class MockRequest() in desktop/libs/notebook/src/notebook/models.py ?
Old code:
`class MockRequest():
  def __init__(self, user, ):
    self.user = user
    self.POST = {}`

New code:
`class MockRequest():
  def __init__(self, user, fs=None, jt=None):
    self.user = user
    self.fs = fs
    self.jt = jt
    self.POST = {}`

**Comment by romainr** [comment]
:+1: 

This should make https://github.com/cloudera/hue/blob/master/desktop/libs/notebook/src/notebook/connectors/oozie_batch.py#L59 pass (but might fail a bit later, would need to test)

**Comment by stephbat** [comment]
I changed the code of desktop/libs/notebook/src/notebook/models.py as proposed, and I get the same message "MockRequest instance has no attribute 'fs'". 
I let you definitively fix this

**Comment by Akhilsnaik** [comment]
@stephbat  , i tested i with the changes propsed by @romainr  , the suggested changes works well and spark job executed after i restarted hue .
<img width="515" alt="Screenshot 2021-02-11 at 11 11 36 AM" src="https://user-images.githubusercontent.com/18462803/107605686-e8e2d100-6c59-11eb-9e7e-4d19319e2e97.png">

**Comment by stephbat** [comment]
@Akhilsnaik @romainr : I confirm that message "MockRequest instance has no attribute 'fs'" disapear with this fix (I forgot to restart HUE during my first try), but I get a new message "MockRequest instance has no attribute 'GET'" with the following error in the logs:

`Traceback (most recent call last):
  File "/usr/share/hue/desktop/libs/notebook/src/notebook/decorators.py", line 114, in wrapper
    return f(*args, **kwargs)
  File "/usr/share/hue/desktop/libs/notebook/src/notebook/api.py", line 318, in fetch_result_data
    response = _fetch_result_data(request.user, notebook, snippet, operation_id, rows=rows, start_over=start_over)
  File "/usr/share/hue/desktop/libs/notebook/src/notebook/api.py", line 329, in _fetch_result_data
    'result': get_api(request, snippet).fetch_result(notebook, snippet, rows, start_over)
  File "/usr/share/hue/desktop/libs/notebook/src/notebook/connectors/oozie_batch.py", line 112, in fetch_result
    log_output = self.get_log(notebook, snippet)
  File "/usr/share/hue/desktop/libs/notebook/src/notebook/connectors/oozie_batch.py", line 138, in get_log
    logs = self._get_log_output(oozie_job)
  File "/usr/share/hue/desktop/libs/notebook/src/notebook/connectors/oozie_batch.py", line 177, in _get_log_output
    q = self.request.GET.copy()
AttributeError: MockRequest instance has no attribute 'GET'
`

**Comment by romainr** [comment]
Similarly to `self.POST = {}` might need the same for GET.

Feel free to send a PR if it works as this should be an easy change.

**Comment by stephbat** [comment]
@romainr : I can test a new fix but I'm not python developer. 
Could you provide the change to apply in /usr/share/hue/desktop/libs/notebook/src/notebook/connectors/oozie_batch.py

**Comment by stephbat** [comment]
@romainr : could you provide me the change to apply in /usr/share/hue/desktop/libs/notebook/src/notebook/connectors/oozie_batch.py ?
Thanks in advance

**Comment by romainr** [comment]
As it is a simple change, would recommend to just click on the 'Edit' button in GitHub, do the change and it will then ask for sending a pull request?

When the changes go it, it will show-up automatically in the latest docker image or this one can be recompiled locally https://github.com/cloudera/hue/tree/master/tools/docker/hue

**Comment by stephbat** [comment]
@romainr : ok I can try to apply the change but what's exactly the content of the change ?

**Comment by stephbat** [comment]
@romainr : Could you please provide me the code to change in /usr/share/hue/desktop/libs/notebook/src/notebook/connectors/oozie_batch.py ? I would like to test it before submit a PR
thanks in advance

**Comment by stephbat** [comment]
I finally modified the class MockRequest() in desktop/libs/notebook/src/notebook/models.py with the following code and the error disapeared
`class MockRequest():
    def __init__(self, user, fs=None, jt=None):
        self.user = user
        self.fs = fs
        self.jt = jt
        self.POST = {}
        self.GET = {}`

**Comment by stephbat** [comment]
PR: https://github.com/cloudera/hue/pull/1793
