### ISSUE TITLE
Build with hadoop2.6.0  method org.apache.hadoop.util.StringUtils.join(java.lang.CharSequence,java.lang.Object[]) is not applicable

### ISSUE THREAD

**Issue by chuckpu** [cloudera/hue#162]
[WARNING] /opt/hue/desktop/libs/hadoop/java/src/main/java/org/apache/hadoop/thriftfs/ThriftHandlerBase.java: Recompile with -Xlint:deprecation for details.
[WARNING] /opt/hue/desktop/libs/hadoop/java/src/main/gen-java/org/apache/hadoop/thriftfs/api/Stat.java: Some input files use unchecked or unsafe operations.
[WARNING] /opt/hue/desktop/libs/hadoop/java/src/main/gen-java/org/apache/hadoop/thriftfs/api/Stat.java: Recompile with -Xlint:unchecked for details.
[INFO] 4 warnings 
[INFO] -------------------------------------------------------------
[INFO] -------------------------------------------------------------
[ERROR] COMPILATION ERROR : 
[INFO] -------------------------------------------------------------
[ERROR] /opt/hue/desktop/libs/hadoop/java/src/main/java/org/apache/hadoop/thriftfs/ThriftUtils.java:[97,40] no suitable method found for join(java.lang.String,java.util.List<java.lang.Object>)
    method org.apache.hadoop.util.StringUtils.join(java.lang.CharSequence,java.lang.Object[]) is not applicable
      (actual argument java.util.List<java.lang.Object> cannot be converted to java.lang.Object[] by method invocation conversion)
    method org.apache.hadoop.util.StringUtils.join(java.lang.CharSequence,java.lang.String[]) is not applicable
      (actual argument java.util.List<java.lang.Object> cannot be converted to java.lang.String[] by method invocation conversion)
    method org.apache.hadoop.util.StringUtils.join(java.lang.CharSequence,java.lang.Iterable<java.lang.String>) is not applicable
      (actual argument java.util.List<java.lang.Object> cannot be converted to java.lang.Iterable<java.lang.String> by method invocation conversion)
[INFO] 1 error
[INFO] -------------------------------------------------------------
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 18.708 s
[INFO] Finished at: 2015-03-19T22:57:50+08:00
[INFO] Final Memory: 16M/245M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.0:compile (default-compile) on project hue-plugins: Compilation failure
[ERROR] /opt/hue/desktop/libs/hadoop/java/src/main/java/org/apache/hadoop/thriftfs/ThriftUtils.java:[97,40] no suitable method found for join(java.lang.String,java.util.List<java.lang.Object>)
[ERROR] method org.apache.hadoop.util.StringUtils.join(java.lang.CharSequence,java.lang.Object[]) is not applicable
[ERROR] (actual argument java.util.List<java.lang.Object> cannot be converted to java.lang.Object[] by method invocation conversion)
[ERROR] method org.apache.hadoop.util.StringUtils.join(java.lang.CharSequence,java.lang.String[]) is not applicable
[ERROR] (actual argument java.util.List<java.lang.Object> cannot be converted to java.lang.String[] by method invocation conversion)
[ERROR] method org.apache.hadoop.util.StringUtils.join(java.lang.CharSequence,java.lang.Iterable<java.lang.String>) is not applicable
[ERROR] (actual argument java.util.List<java.lang.Object> cannot be converted to java.lang.Iterable<java.lang.String> by method invocation conversion)
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
make[2]: *** [/opt/hue/desktop/libs/hadoop/java-lib/hue-plugins-3.7.0-SNAPSHOT.jar] Error 1
make[2]: Leaving directory `/opt/hue/desktop/libs/hadoop'
make[1]: *** [.recursive-env-install/libs/hadoop] Error 2
make[1]: Leaving directory `/opt/hue/desktop'
make: *** [desktop] Error 2

**Comment by romainr** [comment]
Did you change anything or just did a 'git clone ..', then 'make apps'?

**Comment by chuckpu** [comment]
I want to install hue with apache hadoop 2.6.0
I hava changed following https://github.com/cloudera/hue/wiki
<hadoop-mr1.version>1.2.1</hadoop-mr1.version>
    <hadoop.version>2.6.0</hadoop.version>

**Comment by romainr** [comment]
These are very old instructions, you should not need to change anything now (especially if you use YARN, the Java plugins are not even used anymore).

Will update them soon.
